export type ThemeToken =
  | '--ca-barBg'
  | '--ca-barShadow'
  | '--ca-barBorder'
  | '--ca-barRadius'
  | '--ca-btnColor'
  | '--ca-btnHoverBg'
  | '--ca-btnActiveBg'
  | '--ca-btnActiveColor'
  | '--ca-btnActiveGlow'
  | '--ca-btnRadius'
  | '--ca-dividerColor'
  | '--ca-tooltipBg'
  | '--ca-tooltipColor'

export type ThemeName =
  | 'light-pill'
  | 'light-soft'
  | 'light-sharp'
  | 'dark-pill'
  | 'dark-soft'
  | 'dark-sharp'
  | 'neon-pill'
  | 'neon-soft'
  | 'neon-sharp'
  | 'olive-pill'
  | 'olive-soft'
  | 'olive-sharp'